name: sverd_barbershop
description: "A mobile booking application for Sverd Barbershop (Offline Hive Version)."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  flutter_secure_storage: ^9.0.0

  smooth_page_indicator: ^1.1.0
  image_picker: ^1.0.4
  
  path: ^1.8.3
  http: ^1.1.0

  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.2
  geocoding: ^3.0.0
  permission_handler: ^12.0.1

  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  url_launcher: ^6.2.6

  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/photos/
